# inherit from the proprietary version
-include vendor/Hisense/EG929/BoardConfigVendor.mk
LOCAL_PATH := device/Hisense/EG929

# CPU
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7627a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_CPU_VARIANT := Cortex-A5

# Name
TARGET_BOOTLOADER_BOARD_NAME := EG929

# kernel
BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom loglevel=1 vmalloc=200M
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0xD42000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0xD42000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x1C200000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x74A58000
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := $(LOCAL_PATH)/kernel

BOARD_HAS_NO_SELECT_BUTTON := true

TARGET_USERIMAGES_USE_EXT4         := true
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"

# camera
USE_CAMERA_STUB := true

# recovery
TARGET_PREBUILT_RECOVERY_KERNEL := $(LOCAL_PATH)/kernel
